<x-layout title="Homepage">
    <div class="container pt-5 mt-5">
        <div class="row pt-5 mt-5">
            <div class="col-12 d-flex justify-content-center pt-5 mt-5">
                <img src="/media/Group (1).png" alt="diamond" width="40px">
            </div>
            <div class="col-12 text-center pt-2 mt-4">
                <h1 class="text-white">
                    Discover and collect<br> super rare NFTs
                </h1>
                <p class="lead text-white pt-2">
                    Digital marketplace for crypto collectibles and NFTs. Buy, sell,<br>
                    and discover exclusive digital assets today.
                </p>
                <button class="btn-custom rounded-pill">Connect Wallet</button>
            </div>
            <div class="col-12 d-flex justify-content-center pt-5 mt-5">
                <img src="/media/Characters.png" alt="character" width="1050">
            </div>
        </div>
    </div>

    <!-- slider -->
    <div class="container-fluid bg-slider d-flex justify-content-center align-items-center p-5">
        <x-slider />
    </div>

    <!-- collection -->
    <div class="container collection pt-5 mt-5">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white">
                    A new wave of collectibles is<br> about to hit the blockchain.
                </h2>

                <p class="lead text-white pt-3">
                    Characterised by soft lighting, vintage colour schemes and quirky costumes, these generative<br> 3D TinyFaces are the addition to your NFT collection you’ve been waiting for.
                </p>
            </div>

            <div class="col-6 py-5 my-5">
                <img src="/media/Group 71.png" alt="Goup-71" class="img-fluid">
            </div>
            <div class="col-6 d-flex align-items-end flex-column pt-5 mt-5">
                <p class="cat pt-5 mt-5">About</p>
                <h4 class="text-white">Thousands of unique NFTs</h4>
                <p class="lead text-white">
                    Each character is entirely unique and is generated by combining attributes such as colour palettes, skin tones, facial traits, outfits and accessories. With nearly endless combinations, all characters are guaranteed to be one of a kind.
                </p>
                <button class="button-custom rounded-pill" role="button"><span class="text rounded-pill">Place A bid</span></button>
            </div>

            <div class="col-5 d-flex align-items-start flex-column pt-5 mt-5">
                <p class="cat pt-5 mt-5">About</p>
                <h4 class="text-white">Secure the most rare</h4>
                <p class="lead text-white">
                    Even though no two Tinyfaces will ever be the same, some variations are rarer than others. Watch out for special accessories and raw materials - the rarer the attributes, the rarer your character will be.
                </p>
                <button class="button-custom rounded-pill" role="button"><span class="text rounded-pill">Place A bid</span></button>
            </div>

            <div class="col-7 py-5 my-5 d-flex justify-content-end">
                <img src="/media/Group 72.png" alt="Goup-72" class="img-fluid">
            </div>
        </div>
    </div>

    <div class="element-1 container-fluid">
        <img src="/media/Effects 1.png" class="img-fluid">
    </div>
</x-layout>